
%define BIOS_COLOR_BLACK 0x0
%define BIOS_COLOR_BLUE 0x1
%define BIOS_COLOR_GREEN 0x2
%define BIOS_COLOR_CYAN 0x3
%define BIOS_COLOR_RED 0x4
%define BIOS_COLOR_MAGENTA 0x5
%define BIOS_COLOR_BROWN 0x6
%define BIOS_COLOR_LIGHT_GRAY 0x7
%define BIOS_COLOR_DARK_GRAY 0x8
%define BIOS_COLOR_LIGHT_BLUE 0x9
%define BIOS_COLOR_LIGHT_GREEN 0xA
%define BIOS_COLOR_LIGHT_CYAN 0xB
%define BIOS_COLOR_LIGHT_RED 0xC
%define BIOS_COLOR_LIGHT_MAGENTA 0xD
%define BIOS_COLOR_YELLOW 0xE
%define BIOS_COLOR_WHITE 0xF